### ISSUE TITLE
DEPRECATION: https://deprecations.emberjs.com/v3.x/#toc_computed-property-volatile

### ISSUE THREAD

**Issue by rogeraraujo90** [BBVAEngineering/ember-network-state#118]
There is a deprecation in `network` service.

The `remaining`property is using `Computed Property Volatility` that is deprecated and will be removed on Ember 4

There is someone working to convert this service to use Native Class? It can be a simple getter. Can I open a PR?

**Comment by adrigzr** [comment]
Hi @rogeraraujo90,

Thanks for the warning, I will try to update the addon to latest version and remove deprecations.

**Comment by rogeraraujo90** [comment]
Good!
